const textData = {
  D: ['D', 'mm'],
  d: ['d', 'mm'],
  L: ['Skok', 'mm'],
  Q: ['Q', 'L/min'],
  p: ['ρ', 'bar'],
  n: ['ν', 'ob/min'],
  P: ['Moc silnika', 'kW'],
  I: ['Prąd', 'A'],
  VFU: ['Pompa', 'cm³/ob'],
  pipeP: ['Przelot przewodu P'],
  pipeT: ['Przelot przewodu T'],
  pipeS: ['Przelot przewodu ssania'],
  VD: [ 'Nadtłokowa objętość', 'L' ],
  Vd: [ 'Podtłokowa objętość', 'L' ],
  tOut: [ 'Czas wysuw', 'sec' ],
  tIn: [ 'Czas wsuw', 'sec' ],
  tC: [ 'Czas cykl', 'sec' ],
  FOut: [ 'Siła wysuwu', 'kG' ],
  FIn: [ 'Siła wsuwu', 'kG' ],
  vOut: [ 'Szybkość  wysuwu', 'mm/s' ],
  vIn: [ 'Szybkość  wsuwu', 'mm/s' ],
  wall: [ 'Ścianka cylindra', 'mm' ],
  QBack: [ 'Powrót oleju', 'l/min' ],
  tank: [ 'Pojemność zbiornika', 'L' ],
  Power: [ 'Moc silnika', 'kW' ],
};
export const text = (key) => textData[key].join(', ');